## YMAL DOESN'T ALLOW \t ; USE SPACES !
2017:
   common:
          grl: ""
   
   taujet:
          mc_path: /home/sbahrase/WorkDesk/SAMPLES/HBSM/nTuples/2017/mc_1017v03/
          mc_prefix: "user."
          mc_pattern: '*hist-output.root*'
          mc_treename: 'NOMINAL'
          mc_sampletype:
          data_path:
          data_prefix: 
          data_pattern: '*hist-output.root*'
          data_treename: 'NOMINAL'
          data_sampletype:
