## YMAL DOESN'T ALLOW \t ; USE SPACES !
"2016":
  common:
    grl: ""
    
  taujet:
    mc_path: /home/sbahrase/WorkDesk/HPlusTauNu/AnaNTUPs/merged_ntups_1017v01/
    mc_prefix: #"user."
    mc_pattern: '*hist-output.root*.nn'
    mc_treename: 'NOMINAL'
    mc_sampletype:
    data_path: /home/sbahrase/WorkDesk/HPlusTauNu/AnaNTUPs/merged_ntups_1017v01/
    data_prefix: "data" 
    data_pattern: 'full_data_1017v01.root'
    data_treename: 'NOMINAL'
    data_sampletype:

"2017":
  common:
    grl: ""
    
  taujet:
    mc_path: /home/sbahrase/WorkDesk/HPlusTauNu/AnaNTUPs/merged_ntups_1017v01/
    mc_prefix: #"user."
    mc_pattern: '*hist-output.root*.nn'
    mc_treename: 'NOMINAL'
    mc_sampletype:
    data_path: /home/sbahrase/WorkDesk/HPlusTauNu/AnaNTUPs/merged_ntups_1017v01/
    data_prefix: "data" 
    data_pattern: 'full_data_1017v01.root'
    data_treename: 'NOMINAL'
    data_sampletype:
      
"2018":
  common:
    grl: ""
   
  taujet:
    mc_path: /home/sbahrase/WorkDesk/SAMPLES/HBSM/nTuples/2018/18v01/mc/
    mc_prefix: "user."
    mc_pattern: '*hist-output.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
    data_path: /home/sbahrase/WorkDesk/SAMPLES/HBSM/nTuples/2018/18v01/data/
    data_prefix: "user."
    data_pattern: '*hist-output.root*'
    data_treename: 'NOMINAL'
    data_sampletype:
            
