## YMAL DOESN'T ALLOW \t ; USE SPACES !
"2015":
  common:
    grl: ""
    
  taujet:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/mc16/
    mc_prefix: #"user."
    mc_pattern: '*.root'
    mc_treename: 'NOMINAL'
    mc_sampletype:
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/data/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/MC/
    mc_prefix: #"user."ata  
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:

  taulep:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:

"2016":
  common:
    grl: ""
    
  taujet:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:

  taulep:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:

"2017":
  common:
    grl: ""
    
  taujet:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:
      
  taulep:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/Data/
>>>>>>> Stashed changes
    data_prefix: # "user." 
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:

"2018":
  common:
    grl: ""
   
  taujet:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taujet/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taujets/Data/
>>>>>>> Stashed changes
    data_prefix: # "user."
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:
            
  taulep:
<<<<<<< Updated upstream
    mc_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/mc16/
=======
    mc_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/MC/
>>>>>>> Stashed changes
    mc_prefix: #"user."
    mc_pattern: '*.root*'
    mc_treename: 'NOMINAL'
    mc_sampletype:
<<<<<<< Updated upstream
    data_path: /eos/atlas/atlascerngroupdisk/phys-higgs/HSG6/Htaunu/v06/taulep/data/
=======
    data_path: /xdata/eparrish/HPlusNTuples/2018/v06/taulep/Data/
>>>>>>> Stashed changes
    data_prefix: # "user."
    data_pattern: '*.root*'
    data_treename: 'NOMINAL'
    data_sampletype:
            