#!/usr/bin/env python

"""
* This script is for producing final analysis plots.
* input is a ROOT TFile containing all the kinemtatics
* of different samples for  different regions(CR / SR).
* output is a dir containig all the plots.
"""

## stdl-lib
import sys, os
from collections import OrderedDict

# - - - - - - - - - parse plot args (needed before ROOT)
from hpana.cmd import get_plotting_parser 
plotting_parser = get_plotting_parser()
PLOTTING_ARGS = plotting_parser.parse_args()

## local
from hpana.config import Configuration
from hpana.analysis import Analysis
from hpana.plotting  import draw
from hpana import log

# - - - - - - - -  set log level
log.setLevel(PLOTTING_ARGS.log)

# - - - - - - - - Speed things up a bit
import ROOT
ROOT.SetSignalPolicy(ROOT.kSignalFast)
ROOT.gROOT.SetBatch(True)
log.info("ROOT is in batch mode")

# - - - - - - - - build analysis main configuration object
config = Configuration(
    PLOTTING_ARGS.channel,
    mc_campaign=PLOTTING_ARGS.mc_campaign,
    ntuples_version=PLOTTING_ARGS.ntuples_version)

# - - - - - - - - instantiate the analysis
analysis = Analysis(config)

backgrounds = analysis.backgrounds
data = analysis.data

# - - - - - - - - some checks on cmd args
if PLOTTING_ARGS.fields:
    fields = filter(lambda v: v.name in PLOTTING_ARGS.fields, config.variables)
else:
    fields = config.variables
    
if PLOTTING_ARGS.categories:
    categories = filter(lambda c: c.name in PLOTTING_ARGS.categories, config.categories)
else:
    categories = config.categories
    
if PLOTTING_ARGS.systematics:
    #WIP: filter based on the list of systematics available
    systematics = PLOTTING_ARGS.systematics
else:
    systematics = ["NOMINAL"]

# - - - - if you wish to look at specific samples
if PLOTTING_ARGS.backgrounds:
     backgrounds = filter(lambda s: s.name in PLOTTING_ARGS.backgrounds, analysis.backgrounds)

# - - - - if you wish to look at specific samples
if PLOTTING_ARGS.signals:
     signals = filter(lambda s: s.name in PLOTTING_ARGS.signals, analysis.signals)

if PLOTTING_ARGS.no_data:
   data = None

# - - - - - - - - do the plots
for var in fields:
    for cat in categories:
        draw(PLOTTING_ARGS.hists_file, var, cat,
             backgrounds=backgrounds,
             data=data,
             signals=[],
             show_ratio=not PLOTTING_ARGS.no_ratio,
             show_pvalue=not PLOTTING_ARGS.no_pvalue)
            
