#!/usr/bin/env python

"""
* This script is for producing final analysis plots.
* input is a ROOT TFile containing all the kinemtatics
* of different samples for  different regions(CR / SR).
* output is a dir containig all the plots.
"""

## stdl-lib
import sys, os
from collections import OrderedDict
from argparse import ArgumentParser

## local
from hpana.config import Configuration
from hpana.analysis import Analysis
from hpana.plotting  import draw

# - - - - - - - - setup cmd args
parser =  ArgumentParser()
parser.add_argument('hfile', help='histograms root file')
parser.add_argument('--pdir', '-pd', help='plots path', default="./plots")
parser.add_argument('--var', '-v', help="variables to draw")
parser.add_argument('--category', '-c', help="category selections")
args = parser.parse_args()

# - - - - - - - - setup ROOT
import ROOT

# - - - - - - - - instantiate the analysis
config = Configuration("taujet", "2016")
analysis = Analysis(config)
backgrounds = analysis.backgrounds
data = analysis.data

# - - - - - - - - do the plots
for var in config.variables:
    for cat in config.categories:
        draw(args.hfile, var, cat,
             backgrounds=backgrounds,
             data=None,
             show_ratio=False,
             show_pvalue=True)
            
