"""
List of braches to read when caching TTrees,
MAKE it as smalle as possible if you're looking for an actuall boost.  
"""


## - - - list of branche to read to memory
MEM_BRANCHES = {}

MEM_BRANCHES["taulep"] = [
    "HLT_e120_lhloose",
    "HLT_e140_lhloose_nod0",
    "HLT_e24_lhmedium_L1EM20VH",
    "HLT_e26_lhtight_nod0_ivarloose",
    "HLT_e60_lhmedium",
    "HLT_e60_lhmedium_nod0",
    "HLT_e60_medium",
    "HLT_mu20_iloose_L1MU15",
    "HLT_mu24_imedium",
    "HLT_mu26_imedium",
    "HLT_mu26_ivarmedium",
    "HLT_mu40",
    "HLT_mu50",
    "HLT_xe100_L1XE50",
    "HLT_xe110_mht_L1XE50",
    "HLT_xe120_pufit",
    "HLT_xe120_tc_lcw_L1XE50",
    "HLT_xe70_mht",
    "HLT_xe70_tc_lcw",
    "HLT_xe80_tc_lcw_L1XE50",
    "HLT_xe90_mht_L1XE50",
    
    "HLT_xe90_pufit_L1XE50",
    "HLT_xe100_pufit_L1XE55",
    "HLT_xe100_pufit_L1XE55",
    "HLT_xe110_pufit_L1XE50",
    "HLT_xe110_pufit_L1XE55",
    
    "NOMINAL_pileup_random_run_number",
    "PRWHash",

    "bjet_0_b_tag_score",
    "bjet_0_flavorlabel",
    "bjet_0_p4",
    "bjet_0_width",
    "bjet_1_p4",

    "el_0",
    "el_0_id_loose",
    "el_0_id_medium",
    "el_0_id_tight",
    "el_0_iso_FixedCutLoose",
    "el_0_iso_FixedCutTight",
    "el_0_iso_Gradient",
    "el_0_iso_GradientLoose",
    "el_0_iso_Loose",

    "el_0_met_dphi",
    "el_0_met_mt",
    "el_0_met_mt2",

    "el_0_p4",
    "el_0_q",
    "el_0_sf_NOMINAL_EleEffSF_Isolation_MediumLLH_d0z0_v13_isolFixedCutTight",
    
    "el_0_sf_NOMINAL_EleEffSF_Isolation_TightLLH_d0z0_v13_isolFixedCutTight",
    "el_0_sf_NOMINAL_EleEffSF_Isolation_TightLLH_d0z0_v13_isolGradient",

        "el_0_sf_NOMINAL_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2017_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFixedCutTight",
    "el_0_sf_NOMINAL_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2017_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient",
    "el_0_sf_NOMINAL_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2017_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolLoose",
    "el_0_sf_NOMINAL_EleEffSF_offline_RecoTrk",
    "el_0_sf_NOMINAL_EleEffSF_offline_TightLLH_d0z0_v13",

    "el_0_sf_NOMINAL_efficiency_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2017_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFixedCutTight",
    "el_0_sf_NOMINAL_efficiency_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2017_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient",
    "el_0_trig_HLT_e120_lhloose",
    "el_0_trig_HLT_e140_lhloose_nod0",
    "el_0_trig_HLT_e24_lhmedium_L1EM20VH",
    "el_0_trig_HLT_e26_lhtight_nod0_ivarloose",
    "el_0_trig_HLT_e300_etcut",
    "el_0_trig_HLT_e60_lhmedium",
    "el_0_trig_HLT_e60_lhmedium_nod0",
    "el_0_trig_HLT_e60_medium",
    "el_0_trig_trigger_matched",

    "el_0_truth_match",
    "el_0_type",

    "event_number",

    "jet_0_b_tag_score",
    "jet_0_btag_discriminant_MV2c10",
    "jet_0_flavorlabel",
    "jet_0_p4",
    "jet_0_width",

    "jet_1_b_tag_score",
    "jet_1_btag_discriminant_MV2c10",
    "jet_1_p4",
    "jet_1_width",
    
    "jet_sf_NOMINAL_central_jets_global_effSF_JVT",
    "jet_sf_NOMINAL_central_jets_global_ineffSF_JVT",
    "jet_sf_NOMINAL_global_effSF_MV2c10",
    "jet_sf_NOMINAL_global_ineffSF_MV2c10",
    
    "met_HLT_et",
    "met_L1_et",
    "met_p4",
    "met_sig",
    "met_sig_tracks",
    "met_sumet",
    
    "mu_0",
    "mu_0_id_loose",
    "mu_0_id_medium",
    "mu_0_id_tight",

    "mu_0_iso_FixedCutTight",
    "mu_0_iso_Gradient",
    "mu_0_iso_GradientLoose",
    "mu_0_iso_Loose",

    "mu_0_met_dphi",
    "mu_0_met_mt",
    "mu_0_met_mt2",
    "mu_0_muonAuthor",
    "mu_0_muonType",
    "mu_0_origin",
    "mu_0_p4",
    "mu_0_q",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu20_iloose_L1MU15_OR_HLT_mu50_QualTight_IsoNone",
  
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_iloose_OR_HLT_mu24_iloose_L1MU15_OR_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_iloose_OR_HLT_mu24_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_imedium_OR_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_imedium_OR_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_IsoFixedCutTight",

    "mu_0_sf_NOMINAL_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_NOMINAL_MuEffSF_Reco_QualTight",
    "mu_0_sf_NOMINAL_MuEffSF_TTVA",
    "mu_0_trig_HLT_mu20_iloose_L1MU15",
    "mu_0_trig_HLT_mu24_imedium",
    "mu_0_trig_HLT_mu26_imedium",
    "mu_0_trig_HLT_mu26_ivarmedium",
    "mu_0_trig_HLT_mu40",
    "mu_0_trig_HLT_mu50",
    "mu_0_trig_trigger_matched",

    "mu_0_truth_match",
    "mu_0_type",
    
    "n_bjets",
    "n_electrons",
    "n_jets",
    "n_muons",
    "n_photons",
    "n_pvx",
    "n_taus",
    "n_taus_loose",
    "n_taus_medium",

    "n_vx",
    "run_number",
    
    "tau_0",
    "tau_0_allTrk_eta",
    "tau_0_allTrk_n",
    "tau_0_allTrk_phi",
    "tau_0_allTrk_pt",
    "tau_0_b_tag_score",
    "tau_0_b_tagged",
    "tau_0_decay_mode",
    "tau_0_ele_BDTEleScoreTrans_run2",
    "tau_0_ele_bdt_eff_sf",
    "tau_0_ele_bdt_loose",
    "tau_0_ele_bdt_medium",
    "tau_0_ele_bdt_score",
    "tau_0_ele_bdt_tight",
    "tau_0_ele_col_m",
    "tau_0_ele_col_x1",
    "tau_0_ele_col_x2",
    "tau_0_ele_m",
    "tau_0_ele_match_lhscore",
    "tau_0_ele_olr_pass",
    "tau_0_jet_bdt_loose",
    "tau_0_jet_bdt_medium",
    "tau_0_jet_bdt_score",
    "tau_0_jet_bdt_score_trans",
    "tau_0_jet_bdt_tight",
    "tau_0_jet_jvt",
    "tau_0_jet_width",
    "tau_0_jet_width_trks_dr04",
    "tau_0_leadTrk_eta",
    "tau_0_leadTrk_phi",
    "tau_0_leadTrk_pt",
    "tau_0_met_dphi",
    "tau_0_met_mt",
    "tau_0_met_mt2",
    "tau_0_mu_col_m",
    "tau_0_mu_col_x1",
    "tau_0_mu_col_x2",
    "tau_0_mu_m",
    "tau_0_n_all_tracks",
    "tau_0_n_charged_tracks",

    "tau_0_n_wide_tracks",
    "tau_0_origin",
    "tau_0_p4",
    "tau_0_q",
    "tau_0_sf_NOMINAL_TauEffSF_HadTauEleOLR_tauhad",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTloose",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTmedium",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTtight",
    "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_NOMINAL_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_NOMINAL_TauEffSF_reco",
    "tau_0_sf_NOMINAL_TauEffSF_selection",

    "tau_0_trig_HLT_tau125_medium1_tracktwo",
    "tau_0_trig_HLT_tau160_medium1_tracktwo",
    "tau_0_trig_HLT_tau160_medium1_tracktwo_L1TAU100",
    "tau_0_trig_HLT_tau80_medium1_tracktwo",
    "tau_0_trig_HLT_tau80_medium1_tracktwo_L1TAU60",
    "tau_0_trig_trigger_matched",
    "tau_0_type",
    "tau_0_upsilon_energy_based",
    "tau_0_upsilon_pt_based",
    
    "true_tau_0_decay_mode",
    "true_tau_0_isEle",
    "true_tau_0_isHadTau",
    "true_tau_0_isJet",
    "true_tau_0_isMuon",
    "true_tau_0_isTau",
    "true_tau_0_jet_pdgId",
    "true_tau_0_mother_pdgId",
    "true_tau_0_mother_status",

    "true_tau_0_pdgId",
    "true_tau_0_pz",
    "true_tau_0_q",
    "true_tau_0_status",
    "true_tau_0_type",
  
    "weight_mc",
    "weight_total",
]


MEM_BRANCHES["taujet"] = [
    "HLT_3j175",
    "HLT_3j200",
    "HLT_3j225",
    "HLT_4j100",
    "HLT_4j110",
    "HLT_4j120",
    "HLT_4j85",
    "HLT_5j55",
    "HLT_5j60",
    "HLT_5j70_L14J15",
    "HLT_5j85",
    "HLT_6j45",
    "HLT_xe100_L1XE50",
    "HLT_xe100_pufit_L1XE50",
    "HLT_xe100_pufit_L1XE55",
    "HLT_xe100_tc_em_L1XE50",
    "HLT_xe110_mht_L1XE50",
    "HLT_xe110_mht_resurrected",
    "HLT_xe110_pueta_L1XE50",
    "HLT_xe110_pufit_L1XE50",
    "HLT_xe110_pufit_L1XE55",
    "HLT_xe120_pueta",
    "HLT_xe120_pufit",
    "HLT_xe120_tc_lcw_L1XE50",
    "HLT_xe70",
    "HLT_xe70_mht",
    "HLT_xe70_tc_lcw",
    "HLT_xe80_tc_lcw_L1XE50",
    "HLT_xe90_mht_L1XE50",
    "HLT_xe90_pufit_L1XE50",
    "HLT_xe90_mht_wEFMu_L1XE50",
    "HLT_xe90_tc_lcw_wEFMu_L1XE50",

    "HLT_xe110_pufit_xe70_L1XE50",
    "HLT_xe110_pufit_xe65_L1XE50",

    "NOMINAL_pileup_random_run_number",
    "PRWHash",
    
   
    "bjet_0_p4",
    "event_number",
    

    "jet_0_p4",

    "jet_1_p4",

    
    "jet_sf_NOMINAL_central_jets_global_effSF_JVT",
    "jet_sf_NOMINAL_central_jets_global_ineffSF_JVT",
    "jet_sf_NOMINAL_global_effSF_MV2c10",
    "jet_sf_NOMINAL_global_ineffSF_MV2c10",

    "met_p4",

    "n_bjets",
    "n_electrons",
    "n_jets",

    "n_muons",
    "n_photons",
    "n_pvx",
    "n_taus",
   
    "n_vx",
    "run_number",
    
   
    "tau_0_allTrk_pt",
    
    "tau_0_ele_olr_pass",
    "tau_0_jet_bdt_loose",
    "tau_0_jet_bdt_medium",
    "tau_0_jet_bdt_score",
    "tau_0_jet_bdt_score_trans",
    "tau_0_jet_bdt_tight",
    "tau_0_jet_width",
    "tau_0_jet_width_trks_dr04",
    "tau_0_leadTrk_pt",
    "tau_0_met_dphi",
    "tau_0_met_mt",
    "tau_0_met_mt2",
    "tau_0_n_all_tracks",
    "tau_0_n_charged_tracks",

    "tau_0_p4",
    "tau_0_q",
    "tau_0_sf_NOMINAL_TauEffSF_HadTauEleOLR_tauhad",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTloose",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTmedium",
    "tau_0_sf_NOMINAL_TauEffSF_JetBDTtight",
    "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_NOMINAL_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_NOMINAL_TauEffSF_reco",
    "tau_0_sf_NOMINAL_TauEffSF_selection",

    "tau_0_trig_trigger_matched",
    "tau_0_upsilon_energy_based",
    "tau_0_upsilon_pt_based",
    
    
    
    "true_tau_0",

    "true_tau_0_isEle",
    "true_tau_0_isHadTau",
    "true_tau_0_isJet",
    "true_tau_0_isMuon",
    "true_tau_0_isTau",
    "true_tau_0_jet_pdgId",
   
    "weight_mc",
    "weight_total",

    "tau_0_sf_NOMINAL_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_NOMINAL_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_ELEOLR_TOTAL_1up_TauEffSF_HadTauEleOLR_tauhad",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_ELEOLR_TOTAL_1down_TauEffSF_HadTauEleOLR_tauhad",
    "tau_0_sf_NOMINAL_TauEffSF_reco",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_RECO_TOTAL_1up_TauEffSF_reco",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_RECO_TOTAL_1down_TauEffSF_reco",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_RECO_HIGHPT_1up_TauEffSF_reco",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_RECO_HIGHPT_1down_TauEffSF_reco",
    "jet_sf_NOMINAL_central_jets_global_effSF_JVT",
    "jet_sf_NOMINAL_central_jets_global_ineffSF_JVT",
    "jet_sf_NOMINAL_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_0_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_0_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_0_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_0_1up_global_ineffSF_MV2c10",
]

VETO_BRANCHES = {}
VETO_BRANCHES["taujet"] = [
    "HLT_noalg_L1J400",
    "HLT_tau35_medium1_tracktwoEF_xe70_L1XE45",
    "HLT_tau35_medium1_tracktwo_L1TAU20_xe70_L1XE45",
    "HLT_tau35_medium1_tracktwo_xe70_L1XE45",
    "HLT_tau35_mediumRNN_tracktwoMVA_xe70_L1XE45",

    "bjet_0",
    "bjet_0_b_tag_quantile",
    "bjet_0_b_tag_score",
    "bjet_0_b_tagged",
    "bjet_0_cleanJet_EC_LooseBad",
    "bjet_0_fjvt",
    "bjet_0_flavorlabel",
    "bjet_0_flavorlabel_cone",
    "bjet_0_flavorlabel_part",
    "bjet_0_is_Jvt_HS",
    "bjet_0_jvt",
    "bjet_0_origin",
    "bjet_0_q",
    "bjet_0_type",
    "bjet_0_width",

    "event_clean_EC_LooseBad",
    "event_clean_EC_TightBad",

    "jet_0",
    "jet_0_b_tag_quantile",
    # "jet_0_b_tag_score",
    "jet_0_b_tagged",
    "jet_0_btag_discriminant_MV2c10",
    "jet_0_btag_discriminant_MV2c100",
    "jet_0_btag_discriminant_MV2c10rnn",
    "jet_0_cleanJet_EC_LooseBad",
    "jet_0_fjvt",
    "jet_0_flavorlabel",
    "jet_0_flavorlabel_cone",
    "jet_0_flavorlabel_part",
    "jet_0_is_Jvt_HS",
    "jet_0_jvt",
    "jet_0_origin",
    "jet_0_q",
    "jet_0_type",
    "jet_0_width",

    "jet_1",
    "jet_1_b_tag_quantile",
    # "jet_1_b_tag_score",
    "jet_1_b_tagged",
    "jet_1_btag_discriminant_MV2c10",
    "jet_1_btag_discriminant_MV2c100",
    "jet_1_btag_discriminant_MV2c10rnn",
    "jet_1_cleanJet_EC_LooseBad",
    "jet_1_fjvt",
    "jet_1_flavorlabel",
    "jet_1_flavorlabel_cone",
    "jet_1_flavorlabel_part",
    "jet_1_is_Jvt_HS",
    "jet_1_jvt",
    "jet_1_origin",
    "jet_1_q",
    "jet_1_type",
    "jet_1_width",

    "jet_2",
    "jet_2_b_tag_quantile",
    # "jet_2_b_tag_score",
    "jet_2_b_tagged",
    "jet_2_btag_discriminant_MV2c10",
    "jet_2_btag_discriminant_MV2c100",
    "jet_2_btag_discriminant_MV2c10rnn",
    "jet_2_cleanJet_EC_LooseBad",
    "jet_2_fjvt",
    "jet_2_flavorlabel",
    "jet_2_flavorlabel_cone",
    "jet_2_flavorlabel_part",
    "jet_2_is_Jvt_HS",
    "jet_2_jvt",
    "jet_2_origin",
    "jet_2_q",
    "jet_2_type",
    "jet_2_width",

    "met_sig",
    "met_sig_tracks",
    "met_sumet",

    "n_jets_30",
    "n_jets_40",
    "n_jets_bad",
    "n_jets_mc_hs",
    "n_muons_bad",
    "n_muons_loose",
    "n_muons_veryloose",
    "n_photons",
    "n_taus_veryloose",
    "n_truth_jets_pt20_eta45",

    "tau_0_n_all_tracks",
    "tau_0_n_conversion_tracks",
    "tau_0_n_core_tracks",
    "tau_0_n_failTrackFilter_tracks",
    "tau_0_n_fake_tracks",
    "tau_0_n_isolation_tracks",
    "tau_0_n_modified_isolation_tracks",
    "tau_0_n_old_tracks",
    "tau_0_n_passTrkSelectionTight_tracks",
    "tau_0_n_passTrkSelector_tracks",
    "tau_0_n_unclassified_tracks",
    "tau_0_n_wide_tracks",

    "tau_0_trig_HLT_tau125_medium1_tracktwo",
    "tau_0_trig_HLT_tau160_medium1_tracktwo",
    "tau_0_trig_HLT_tau160_medium1_tracktwoEF_L1TAU100",
    "tau_0_trig_HLT_tau160_medium1_tracktwo_L1TAU100",
    "tau_0_trig_HLT_tau160_mediumRNN_tracktwoMVA_L1TAU100",
    "tau_0_trig_HLT_tau200_medium1_tracktwoEF_L1TAU100",
    "tau_0_trig_HLT_tau200_mediumRNN_tracktwoMVA_L1TAU100",
    "tau_0_trig_HLT_tau80_medium1_tracktwo",
    "tau_0_trig_HLT_tau80_medium1_tracktwo_L1TAU60",


    "theory_weights_CT14_pdfset",
    "theory_weights_MMHT_pdfset",
    "theory_weights_PDF_central_value",
    "theory_weights_PDF_error_down",
    "theory_weights_PDF_error_up",
    "theory_weights_alphaS_down",
    "theory_weights_alphaS_up",

    "true_tau_0",
    "true_tau_0_classifierParticleOrigin",
    "true_tau_0_classifierParticleType",
    "true_tau_0_decay_mode",
    "true_tau_0_n_charged",
    "true_tau_0_n_charged_pion",
    "true_tau_0_n_neutral",
    "true_tau_0_n_neutral_pion",
    "true_tau_0_origin",
    "true_tau_0_p4_vis_charged_track0",
    "true_tau_0_p4_vis_charged_track1",
    "true_tau_0_p4_vis_charged_track2",
    "true_tau_0_pz",
    "true_tau_0_q",
    "true_tau_0_vis_charged_p4",
    "true_tau_0_vis_neutral_others_p4",
    "true_tau_0_vis_neutral_p4",
    "true_tau_0_vis_neutral_pions_p4",
]

VETO_BRANCHES["taulep"] = [
    "HLT_tau35_medium1_tracktwo_L1TAU20_xe70_L1XE45",
    "HLT_tau35_medium1_tracktwo_xe70_L1XE45",

    "PRWHash",
    "bjet_0",
    "bjet_0_b_tag_quantile",
    "bjet_0_b_tag_score",
    "bjet_0_b_tagged",
    "bjet_0_cleanJet_EC_LooseBad",
    "bjet_0_fjvt",
    "bjet_0_flavorlabel",
    "bjet_0_flavorlabel_cone",
    "bjet_0_flavorlabel_part",
    "bjet_0_is_Jvt_HS",
    "bjet_0_jvt",
    "bjet_0_origin",
    "bjet_0_q",
    "bjet_0_type",
    "bjet_0_width",

    "el_0",
    "el_0_cluster_eta",
    "el_0_cluster_eta_be2",
    "el_0_id_bad",
    "el_0_id_charge",

    "el_0_met_dphi",
    "el_0_met_mt",
    "el_0_met_mt2",
    "el_0_muonAuthor",
    "el_0_muonType",
    "el_0_origin",

    # "el_0_sf_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_MediumLLH_d0z0_v13",
    # "el_0_sf_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_MediumLLH_d0z0_v13",
    # "el_0_sf_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_MediumLLH_d0z0_v13_FCTight",
    # "el_0_sf_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_MediumLLH_d0z0_v13_Gradient",
    # "el_0_sf_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_MediumLLH_d0z0_v13_FCTight",
    # "el_0_sf_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_MediumLLH_d0z0_v13_Gradient",
    # "el_0_sf_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_RecoTrk",
    # "el_0_sf_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_RecoTrk",

    "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2017",
    "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    # "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_MediumLLH_d0z0_v13_isolFCTight_2015",
    "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolGradient_2015",
    "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2017",
    "el_0_sf_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolFCTight_2015",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolGradient_2015",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2016",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2017",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1down_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2017",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolFCTight_2015",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolGradient_2015",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2016",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2017",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    "el_0_sf_EL_EFF_TriggerEff_TOTAL_1NPCOR_PLUS_UNCOR_1up_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2017",

    "el_0_sf_NOMINAL_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolFCTight_2015",
    "el_0_sf_NOMINAL_efficiency_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolGradient_2015",
    "el_0_sf_NOMINAL_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2016",
    "el_0_sf_NOMINAL_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight_2017",
    "el_0_sf_NOMINAL_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    "el_0_sf_NOMINAL_efficiency_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2017",
    "el_0_sf_NOMINAL_EleEffSF_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_TightLLH_d0z0_v13_isolGradient_2015",
    "el_0_sf_NOMINAL_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2016",
    "el_0_sf_NOMINAL_EleEffSF_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolGradient_2017",

    "el_0_sf_NOMINAL_EleEffSF_Isolation_MediumLLH_d0z0_v13_FCTight",
    "el_0_sf_NOMINAL_EleEffSF_Isolation_MediumLLH_d0z0_v13_Gradient",

    "el_0_trk_d0_sig",
    "el_0_trk_d0",
    "el_0_trk_pt_error",
    "el_0_trk_pvx_z0_sig",
    "el_0_trk_pvx_z0_sintheta",
    "el_0_trk_pvx_z0",
    "el_0_trk_vx_v",
    "el_0_trk_vx",
    "el_0_trk_z0_sig",
    "el_0_trk_z0_sintheta",
    "el_0_trk_z0",
    "el_0_type",

    "event_clean_EC_LooseBad",
    "event_clean_EC_TightBad",

    "jet_0_b_tag_quantile",
    # "jet_0_b_tag_score",
    "jet_0_b_tagged",
    "jet_0_btag_discriminant_MV2c10",
    "jet_0_btag_discriminant_MV2c100",
    "jet_0_btag_discriminant_MV2c10rnn",
    "jet_0_cleanJet_EC_LooseBad",
    "jet_0_fjvt",
    "jet_0_flavorlabel_cone",
    "jet_0_flavorlabel_part",
    "jet_0_flavorlabel",
    "jet_0_is_Jvt_HS",
    "jet_0_jvt",
    "jet_0_origin",
    "jet_0_q",
    "jet_0_type",
    "jet_0_width",
    "jet_0",

    "jet_1_b_tag_quantile",
    # "jet_1_b_tag_score",
    "jet_1_b_tagged",
    "jet_1_btag_discriminant_MV2c10",
    "jet_1_btag_discriminant_MV2c100",
    "jet_1_btag_discriminant_MV2c10rnn",
    "jet_1_cleanJet_EC_LooseBad",
    "jet_1_fjvt",
    "jet_1_flavorlabel_cone",
    "jet_1_flavorlabel_part",
    "jet_1_flavorlabel",
    "jet_1_is_Jvt_HS",
    "jet_1_jvt",
    "jet_1_origin",
    "jet_1_q",
    "jet_1_type",
    "jet_1_width",
    "jet_1",

    "jet_2_b_tag_quantile",
    # "jet_2_b_tag_score",
    "jet_2_b_tagged",
    "jet_2_btag_discriminant_MV2c10",
    "jet_2_btag_discriminant_MV2c100",
    "jet_2_btag_discriminant_MV2c10rnn",
    "jet_2_cleanJet_EC_LooseBad",
    "jet_2_fjvt",
    "jet_2_flavorlabel_cone",
    "jet_2_flavorlabel_part",
    "jet_2_flavorlabel",
    "jet_2_is_Jvt_HS",
    "jet_2_jvt",
    "jet_2_origin",
    "jet_2_q",
    "jet_2_type",
    "jet_2_width",
    "jet_2",

    # "jet_sf_FT_EFF_Eigen_B_0_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_0_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_0_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_0_1up_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_1_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_1_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_1_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_B_1_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_2_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_2_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_2_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_B_2_1up_global_ineffSF_MV2c10",
    
    # "jet_sf_FT_EFF_Eigen_C_0_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_0_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_0_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_0_1up_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_1_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_1_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_1_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_C_1_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_2_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_2_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_2_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_2_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_3_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_3_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_3_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_C_3_1up_global_ineffSF_MV2c10",

    # "jet_sf_FT_EFF_Eigen_Light_0_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_0_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_0_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_0_1up_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_1_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_1_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_1_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_Eigen_Light_1_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_2_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_2_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_2_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_2_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_3_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_3_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_3_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_3_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_4_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_4_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_4_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_Eigen_Light_4_1up_global_ineffSF_MV2c10",

    # "jet_sf_FT_EFF_extrapolation_1down_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_extrapolation_1down_global_ineffSF_MV2c10",
    # "jet_sf_FT_EFF_extrapolation_1up_global_effSF_MV2c10",
    # "jet_sf_FT_EFF_extrapolation_1up_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_extrapolation_from_charm_1down_global_effSF_MV2c10",
    "jet_sf_FT_EFF_extrapolation_from_charm_1down_global_ineffSF_MV2c10",
    "jet_sf_FT_EFF_extrapolation_from_charm_1up_global_effSF_MV2c10",
    "jet_sf_FT_EFF_extrapolation_from_charm_1up_global_ineffSF_MV2c10",

    # "jet_sf_JET_fJvtEfficiency_1down_central_jets_global_effSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1down_central_jets_global_ineffSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1down_forward_jets_global_effSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1down_forward_jets_global_ineffSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1up_central_jets_global_effSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1up_central_jets_global_ineffSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1up_forward_jets_global_effSF_JVT",
    # "jet_sf_JET_fJvtEfficiency_1up_forward_jets_global_ineffSF_JVT",
    # "jet_sf_JET_JvtEfficiency_1down_central_jets_global_effSF_JVT",
    "jet_sf_JET_JvtEfficiency_1down_central_jets_global_ineffSF_JVT",
    "jet_sf_JET_JvtEfficiency_1down_forward_jets_global_effSF_JVT",
    "jet_sf_JET_JvtEfficiency_1down_forward_jets_global_ineffSF_JVT",
    "jet_sf_JET_JvtEfficiency_1up_central_jets_global_effSF_JVT",
    "jet_sf_JET_JvtEfficiency_1up_central_jets_global_ineffSF_JVT",
    "jet_sf_JET_JvtEfficiency_1up_forward_jets_global_effSF_JVT",
    "jet_sf_JET_JvtEfficiency_1up_forward_jets_global_ineffSF_JVT",

    "met_sig_tracks",
    "met_sig",
    "met_sumet",

    "mu_0_cluster_eta_be2",
    "mu_0_cluster_eta",
    "mu_0_id_bad",
    "mu_0_id_charge",
    "mu_0_met_dphi",
    "mu_0_met_mt",
    "mu_0_met_mt2",

    "mu_0_sf_MUON_EFF_ISO_STAT_1down_MuEffSF_IsoFixedCutHighMuTight",
    "mu_0_sf_MUON_EFF_ISO_STAT_1down_MuEffSF_IsoFixedCutPflowTight",
    # "mu_0_sf_MUON_EFF_ISO_STAT_1down_MuEffSF_IsoGradient",
    "mu_0_sf_MUON_EFF_ISO_STAT_1down_MuEffSF_IsoLoose",
    "mu_0_sf_MUON_EFF_ISO_STAT_1up_MuEffSF_IsoFixedCutHighMuTight",
    "mu_0_sf_MUON_EFF_ISO_STAT_1up_MuEffSF_IsoFixedCutPflowTight",
    # "mu_0_sf_MUON_EFF_ISO_STAT_1up_MuEffSF_IsoGradient",
    "mu_0_sf_MUON_EFF_ISO_STAT_1up_MuEffSF_IsoLoose",
    "mu_0_sf_MUON_EFF_ISO_SYS_1down_MuEffSF_IsoFixedCutHighMuTight",
    "mu_0_sf_MUON_EFF_ISO_SYS_1down_MuEffSF_IsoFixedCutPflowTight",
    # "mu_0_sf_MUON_EFF_ISO_SYS_1down_MuEffSF_IsoGradient",
    "mu_0_sf_MUON_EFF_ISO_SYS_1down_MuEffSF_IsoLoose",
    "mu_0_sf_MUON_EFF_ISO_SYS_1up_MuEffSF_IsoFixedCutHighMuTight",
    "mu_0_sf_MUON_EFF_ISO_SYS_1up_MuEffSF_IsoFixedCutPflowTight",
    # "mu_0_sf_MUON_EFF_ISO_SYS_1up_MuEffSF_IsoGradient",
    "mu_0_sf_MUON_EFF_ISO_SYS_1up_MuEffSF_IsoLoose",

    "mu_0_sf_MUON_EFF_RECO_STAT_1down_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_MUON_EFF_RECO_STAT_1down_MuEffSF_Reco_QualMedium",
    # "mu_0_sf_MUON_EFF_RECO_STAT_1down_MuEffSF_Reco_QualTight",
    "mu_0_sf_MUON_EFF_RECO_STAT_1up_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_MUON_EFF_RECO_STAT_1up_MuEffSF_Reco_QualMedium",
    # "mu_0_sf_MUON_EFF_RECO_STAT_1up_MuEffSF_Reco_QualTight",
    "mu_0_sf_MUON_EFF_RECO_SYS_1down_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_MUON_EFF_RECO_SYS_1down_MuEffSF_Reco_QualMedium",
    # "mu_0_sf_MUON_EFF_RECO_SYS_1down_MuEffSF_Reco_QualTight",
    "mu_0_sf_MUON_EFF_RECO_SYS_1up_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_MUON_EFF_RECO_SYS_1up_MuEffSF_Reco_QualMedium",
    # "mu_0_sf_MUON_EFF_RECO_SYS_1up_MuEffSF_Reco_QualTight",

    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu20_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu24_iloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu24_ivarloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu24_L1MU15_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu40_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1down_MuEffSF_HLT_mu60_0eta105_msonly_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu20_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu24_iloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu24_ivarloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu24_L1MU15_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu40_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigStatUncertainty_1up_MuEffSF_HLT_mu60_0eta105_msonly_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu20_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu24_iloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu24_ivarloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu24_L1MU15_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu40_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1down_MuEffSF_HLT_mu60_0eta105_msonly_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu20_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu24_iloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu24_ivarloose_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu24_L1MU15_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu40_QualTight_IsoNone",
    # "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_MUON_EFF_TrigSystUncertainty_1up_MuEffSF_HLT_mu60_0eta105_msonly_QualTight_IsoNone",

    # "mu_0_sf_MUON_EFF_TTVA_STAT_1down_MuEffSF_TTVA",
    # "mu_0_sf_MUON_EFF_TTVA_STAT_1up_MuEffSF_TTVA",
    # "mu_0_sf_MUON_EFF_TTVA_SYS_1down_MuEffSF_TTVA",
    # "mu_0_sf_MUON_EFF_TTVA_SYS_1up_MuEffSF_TTVA",

    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu20_iloose_L1MU15_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_iloose_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_imedium_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_ivarloose_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu24_L1MU15_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_imedium_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_ivarmedium_OR_HLT_mu50_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu26_ivarmedium_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu40_QualTight_IsoNone",
    # "mu_0_sf_NOMINAL_MuEffSF_HLT_mu50_QualTight_IsoNone",
    "mu_0_sf_NOMINAL_MuEffSF_HLT_mu60_0eta105_msonly_QualTight_IsoNone",

    "mu_0_sf_NOMINAL_MuEffSF_IsoFixedCutHighMuTight",
    "mu_0_sf_NOMINAL_MuEffSF_IsoFixedCutPflowTight",
    # "mu_0_sf_NOMINAL_MuEffSF_IsoGradient",
    "mu_0_sf_NOMINAL_MuEffSF_IsoLoose",
    "mu_0_sf_NOMINAL_MuEffSF_Reco_QualHighPt",
    "mu_0_sf_NOMINAL_MuEffSF_Reco_QualMedium",
    # "mu_0_sf_NOMINAL_MuEffSF_Reco_QualTight",

    # "mu_0_sf_NOMINAL_MuEffSF_TTVA",

    "mu_0_trk_d0_sig",
    "mu_0_trk_d0",
    "mu_0_trk_pt_error",
    "mu_0_trk_pvx_z0_sig",
    "mu_0_trk_pvx_z0_sintheta",
    "mu_0_trk_pvx_z0",
    "mu_0_trk_vx_v",
    "mu_0_trk_vx",
    "mu_0_trk_z0_sig",
    "mu_0_trk_z0_sintheta",
    "mu_0_trk_z0",
    "mu_0_type",
    "mu_0",

    "tau_0_n_all_tracks",
    "tau_0_n_conversion_tracks",
    "tau_0_n_core_tracks",
    "tau_0_n_failTrackFilter_tracks",
    "tau_0_n_fake_tracks",
    "tau_0_n_isolation_tracks",
    "tau_0_n_modified_isolation_tracks",
    "tau_0_n_old_tracks",
    "tau_0_n_passTrkSelectionTight_tracks",
    "tau_0_n_passTrkSelector_tracks",
    "tau_0_n_unclassified_tracks",

    # "tau_0_sf_NOMINAL_TauEffSF_HadTauEleOLR_tauhad",
    # "tau_0_sf_NOMINAL_TauEffSF_JetBDTloose",
    # "tau_0_sf_NOMINAL_TauEffSF_JetBDTmedium",
    # "tau_0_sf_NOMINAL_TauEffSF_JetBDTtight",
    # "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDT_electron",
    # "tau_0_sf_NOMINAL_TauEffSF_LooseEleBDTPlusVeto_electron",
    # "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDT_electron",
    # "tau_0_sf_NOMINAL_TauEffSF_MediumEleBDTPlusVeto_electron",
    # "tau_0_sf_NOMINAL_TauEffSF_reco",
    # "tau_0_sf_NOMINAL_TauEffSF_selection",
    # "tau_0_sf_NOMINAL_TauEffSF_VeryLooseLlhEleOLR_electron",

    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1down_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1down_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1down_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1down_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1down_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1up_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1up_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1up_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1up_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16A_1up_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1down_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1down_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1down_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1down_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1down_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1up_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1up_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1up_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1up_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_STATMC16D_1up_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_VeryLooseLlhEleOLR_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_LooseEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_LooseEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_MediumEleBDT_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_MediumEleBDTPlusVeto_electron",
    "tau_0_sf_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_VeryLooseLlhEleOLR_electron",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_ELEOLR_TOTAL_1down_TauEffSF_HadTauEleOLR_tauhad",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_ELEOLR_TOTAL_1up_TauEffSF_HadTauEleOLR_tauhad",

    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1down_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1down_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1up_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2025_1up_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1down_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1down_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1up_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR2530_1up_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1down_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1down_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1up_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORR3040_1up_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1down_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1down_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1down_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1up_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1up_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_1PRONGSTATSYSTUNCORRGE40_1up_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1down_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1down_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1up_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORR2030_1up_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1down_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1down_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1down_TauEffSF_JetBDTtight",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1up_TauEffSF_JetBDTloose",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1up_TauEffSF_JetBDTmedium",
    "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_3PRONGSTATSYSTUNCORRGE30_1up_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1down_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1down_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1down_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1up_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1up_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_HIGHPT_1up_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1down_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1down_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1down_TauEffSF_JetBDTtight",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1up_TauEffSF_JetBDTloose",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1up_TauEffSF_JetBDTmedium",
    # "tau_0_sf_TAUS_TRUEHADTAU_EFF_JETID_SYST_1up_TauEffSF_JetBDTtight",

    "theory_weights_alphaS_down",
    "theory_weights_alphaS_up",
    "theory_weights_CT14_pdfset",
    "theory_weights_LHE3Weight_muR=05,muF=05",
    "theory_weights_LHE3Weight_muR=05,muF=10",
    "theory_weights_LHE3Weight_muR=05,muF=20",
    "theory_weights_LHE3Weight_muR=10,muF=05",
    "theory_weights_LHE3Weight_muR=10,muF=20",
    "theory_weights_LHE3Weight_muR=20,muF=05",
    "theory_weights_LHE3Weight_muR=20,muF=10",
    "theory_weights_LHE3Weight_muR=20,muF=20",
    "theory_weights_MMHT_pdfset",
    "theory_weights_PDF_central_value",
    "theory_weights_PDF_error_down",
    "theory_weights_PDF_error_up",

    # "true_tau_0_classifierParticleOrigin",
    # "true_tau_0_classifierParticleType",
    # "true_tau_0_decay_mode",
    # "true_tau_0_isEle",
    # "true_tau_0_isHadTau",
    # "true_tau_0_isJet",
    # "true_tau_0_isMuon",
    # "true_tau_0_isTau",
    # "true_tau_0_isTruthMatch",
    # "true_tau_0_jet_pdgId",
    # "true_tau_0_mother_pdgId",
    # "true_tau_0_mother_status",
    "true_tau_0_n_charged_pion",
    "true_tau_0_n_charged",
    "true_tau_0_n_neutral_pion",
    "true_tau_0_n_neutral",
    "true_tau_0_origin",
    "true_tau_0_p4_vis_charged_track0",
    "true_tau_0_p4_vis_charged_track1",
    "true_tau_0_p4_vis_charged_track2",
    # "true_tau_0_p4",
    # "true_tau_0_pdgId",
    # "true_tau_0_pz",
    # "true_tau_0_q",
    # "true_tau_0_status",
    # "true_tau_0_type",
    "true_tau_0_vis_charged_p4",
    "true_tau_0_vis_neutral_others_p4",
    "true_tau_0_vis_neutral_p4",
    "true_tau_0_vis_neutral_pions_p4",
]
