// Generated by generate-wtaunu-macros.py, do not edit!


float wtaunu_ckkw15_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.03522586823;
    if (jetBin == 2) return 1.01290869713;
    if (jetBin == 3) return 0.971694171429;
    if (jetBin == 4) return 0.923798263073;
    if (jetBin == 5) return 0.93588924408;
    if (jetBin == 6) return 0.947956204414;
    if (jetBin == 7) return 1.1697678566;
    if (jetBin == 8) return 1.02924108505;
    if (jetBin == 9) return 1.50700521469;
    if (jetBin == 10) return 0.604125320911;
    if (jetBin == 11) return 0.82850664854;
    if (jetBin == 12) return 5.97041797638;
    return 0; // This never happens
}

float wtaunu_ckkw15_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.998174011707;
    if (jetBin == 2) return 0.989318311214;
    if (jetBin == 3) return 0.949764609337;
    if (jetBin == 4) return 0.903175771236;
    if (jetBin == 5) return 0.884770452976;
    if (jetBin == 6) return 0.975511491299;
    if (jetBin == 7) return 1.1332051754;
    if (jetBin == 8) return 1.03983330727;
    if (jetBin == 9) return 1.04343414307;
    if (jetBin == 10) return 1.77262055874;
    if (jetBin == 11) return 3.05426645279;
    if (jetBin == 12) return 0.863859295845;
    return 0; // This never happens
}

float wtaunu_ckkw15_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.947531223297;
    if (jetBin == 2) return 0.959675252438;
    if (jetBin == 3) return 0.904162406921;
    if (jetBin == 4) return 0.83786958456;
    if (jetBin == 5) return 0.845794856548;
    if (jetBin == 6) return 0.89220148325;
    if (jetBin == 7) return 0.929581582546;
    if (jetBin == 8) return 0.952105224133;
    if (jetBin == 9) return 0.894763708115;
    if (jetBin == 10) return 0.941943645477;
    if (jetBin == 11) return 0.813163459301;
    if (jetBin == 12) return 0.874242782593;
    return 0; // This never happens
}

float wtaunu_ckkw15_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.14450550079;
    if (jetBin == 2) return 1.02195811272;
    if (jetBin == 3) return 0.988192558289;
    if (jetBin == 4) return 0.888862371445;
    if (jetBin == 5) return 0.879824697971;
    if (jetBin == 6) return 0.92985188961;
    if (jetBin == 7) return 0.973239302635;
    if (jetBin == 8) return 1.10136032104;
    if (jetBin == 9) return 0.980902194977;
    if (jetBin == 10) return 0.916356027126;
    if (jetBin == 11) return 1.41554498672;
    if (jetBin == 12) return 2.7361831665;
    return 0; // This never happens
}

float wtaunu_ckkw15_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.67888724804;
    if (jetBin == 2) return 0.991843760014;
    if (jetBin == 3) return 0.992511332035;
    if (jetBin == 4) return 0.887812077999;
    if (jetBin == 5) return 0.836147069931;
    if (jetBin == 6) return 0.895834505558;
    if (jetBin == 7) return 0.875725328922;
    if (jetBin == 8) return 0.865620553493;
    if (jetBin == 9) return 1.45049655437;
    if (jetBin == 10) return 0.896775901318;
    if (jetBin == 11) return 1.24804329872;
    if (jetBin == 12) return 0.626957833767;
    return 0; // This never happens
}

float wtaunu_ckkw15_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.67888724804;
    if (jetBin == 2) return 1.18032371998;
    if (jetBin == 3) return 0.941224992275;
    if (jetBin == 4) return 0.98529201746;
    if (jetBin == 5) return 0.954674303532;
    if (jetBin == 6) return 0.945665955544;
    if (jetBin == 7) return 1.40908622742;
    if (jetBin == 8) return 0.869572520256;
    if (jetBin == 9) return 1.92715597153;
    if (jetBin == 10) return 1.72672605515;
    if (jetBin == 11) return 1.24804329872;
    if (jetBin == 12) return 0.0336218513548;
    return 0; // This never happens
}

float wtaunu_ckkw15_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.67888724804;
    if (jetBin == 2) return 1.2434772253;
    if (jetBin == 3) return 0.882482767105;
    if (jetBin == 4) return 0.812213242054;
    if (jetBin == 5) return 0.83333671093;
    if (jetBin == 6) return 0.791880905628;
    if (jetBin == 7) return 1.13073980808;
    if (jetBin == 8) return 0.750469267368;
    if (jetBin == 9) return 0.902483284473;
    if (jetBin == 10) return 0.565406620502;
    if (jetBin == 11) return 2.30494236946;
    if (jetBin == 12) return 0.0336218513548;
    return 0; // This never happens
}

float wtaunu_ckkw15_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.67888724804;
    if (jetBin == 2) return 1.55517709255;
    if (jetBin == 3) return 0.948571264744;
    if (jetBin == 4) return 0.91941434145;
    if (jetBin == 5) return 0.721458852291;
    if (jetBin == 6) return 0.944126725197;
    if (jetBin == 7) return 0.768530964851;
    if (jetBin == 8) return 0.937146067619;
    if (jetBin == 9) return 0.613916039467;
    if (jetBin == 10) return 0.82850664854;
    if (jetBin == 11) return 2.30494236946;
    if (jetBin == 12) return 0.0336218513548;
    return 0; // This never happens
}

float wtaunu_ckkw30_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.03160619736;
    if (jetBin == 2) return 0.990841329098;
    if (jetBin == 3) return 0.956378400326;
    if (jetBin == 4) return 1.00167798996;
    if (jetBin == 5) return 1.02000951767;
    if (jetBin == 6) return 0.966475427151;
    if (jetBin == 7) return 1.0670030117;
    if (jetBin == 8) return 0.972188711166;
    if (jetBin == 9) return 1.189047575;
    if (jetBin == 10) return 0.600271582603;
    if (jetBin == 11) return 0.656334877014;
    if (jetBin == 12) return 0.850695669651;
    return 0; // This never happens
}

float wtaunu_ckkw30_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.953685820103;
    if (jetBin == 2) return 0.992957234383;
    if (jetBin == 3) return 0.992985069752;
    if (jetBin == 4) return 0.993922472;
    if (jetBin == 5) return 0.917628228664;
    if (jetBin == 6) return 0.897612452507;
    if (jetBin == 7) return 0.986543357372;
    if (jetBin == 8) return 0.907512009144;
    if (jetBin == 9) return 1.0028231144;
    if (jetBin == 10) return 1.57827270031;
    if (jetBin == 11) return 0.671852648258;
    if (jetBin == 12) return 1.70067620277;
    return 0; // This never happens
}

float wtaunu_ckkw30_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.964231848717;
    if (jetBin == 2) return 1.01055943966;
    if (jetBin == 3) return 0.98460739851;
    if (jetBin == 4) return 0.941137433052;
    if (jetBin == 5) return 0.874875366688;
    if (jetBin == 6) return 0.822757899761;
    if (jetBin == 7) return 0.799208402634;
    if (jetBin == 8) return 0.771030783653;
    if (jetBin == 9) return 0.750507295132;
    if (jetBin == 10) return 0.653550565243;
    if (jetBin == 11) return 0.649619042873;
    if (jetBin == 12) return 0.779461205006;
    return 0; // This never happens
}

float wtaunu_ckkw30_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.16409504414;
    if (jetBin == 2) return 1.1372834444;
    if (jetBin == 3) return 1.10524535179;
    if (jetBin == 4) return 1.01699256897;
    if (jetBin == 5) return 0.881240308285;
    if (jetBin == 6) return 0.838499724865;
    if (jetBin == 7) return 0.835345685482;
    if (jetBin == 8) return 0.93562656641;
    if (jetBin == 9) return 0.729187309742;
    if (jetBin == 10) return 0.709725916386;
    if (jetBin == 11) return 0.942000389099;
    if (jetBin == 12) return 2.23919582367;
    return 0; // This never happens
}

float wtaunu_ckkw30_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.89830386639;
    if (jetBin == 2) return 1.15130472183;
    if (jetBin == 3) return 1.16187155247;
    if (jetBin == 4) return 1.04109787941;
    if (jetBin == 5) return 0.85484713316;
    if (jetBin == 6) return 0.795219361782;
    if (jetBin == 7) return 0.759095013142;
    if (jetBin == 8) return 0.723199546337;
    if (jetBin == 9) return 1.2048740387;
    if (jetBin == 10) return 0.757708311081;
    if (jetBin == 11) return 0.92604970932;
    if (jetBin == 12) return 0.33517190814;
    return 0; // This never happens
}

float wtaunu_ckkw30_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.89830386639;
    if (jetBin == 2) return 1.35393750668;
    if (jetBin == 3) return 1.10469460487;
    if (jetBin == 4) return 1.11507415771;
    if (jetBin == 5) return 0.925231456757;
    if (jetBin == 6) return 0.837897241116;
    if (jetBin == 7) return 1.20945894718;
    if (jetBin == 8) return 0.654149413109;
    if (jetBin == 9) return 1.5197892189;
    if (jetBin == 10) return 1.28196549416;
    if (jetBin == 11) return 0.92604970932;
    if (jetBin == 12) return 0.0353515483439;
    return 0; // This never happens
}

float wtaunu_ckkw30_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.89830386639;
    if (jetBin == 2) return 1.55037915707;
    if (jetBin == 3) return 1.0461345911;
    if (jetBin == 4) return 0.946591973305;
    if (jetBin == 5) return 0.856809139252;
    if (jetBin == 6) return 0.733562588692;
    if (jetBin == 7) return 0.922178864479;
    if (jetBin == 8) return 0.622723400593;
    if (jetBin == 9) return 0.760102212429;
    if (jetBin == 10) return 0.538535952568;
    if (jetBin == 11) return 1.50284910202;
    if (jetBin == 12) return 0.0353515483439;
    return 0; // This never happens
}

float wtaunu_ckkw30_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.89830386639;
    if (jetBin == 2) return 1.89188528061;
    if (jetBin == 3) return 1.08213186264;
    if (jetBin == 4) return 1.10621118546;
    if (jetBin == 5) return 0.715335845947;
    if (jetBin == 6) return 0.844575822353;
    if (jetBin == 7) return 0.674536943436;
    if (jetBin == 8) return 0.840392529964;
    if (jetBin == 9) return 0.475037813187;
    if (jetBin == 10) return 0.656334877014;
    if (jetBin == 11) return 1.50284910202;
    if (jetBin == 12) return 0.0353515483439;
    return 0; // This never happens
}

float wtaunu_fac025_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.0291210413;
    if (jetBin == 2) return 1.02303731441;
    if (jetBin == 3) return 1.01435792446;
    if (jetBin == 4) return 1.00072312355;
    if (jetBin == 5) return 0.985256910324;
    if (jetBin == 6) return 0.990263879299;
    if (jetBin == 7) return 1.18639099598;
    if (jetBin == 8) return 1.13515198231;
    if (jetBin == 9) return 1.5510879755;
    if (jetBin == 10) return 0.735634744167;
    if (jetBin == 11) return 0.834466159344;
    if (jetBin == 12) return 1.0035803318;
    return 0; // This never happens
}

float wtaunu_fac025_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.0305325985;
    if (jetBin == 2) return 1.03308868408;
    if (jetBin == 3) return 1.00706887245;
    if (jetBin == 4) return 0.975576281548;
    if (jetBin == 5) return 0.91057908535;
    if (jetBin == 6) return 0.944295465946;
    if (jetBin == 7) return 1.07268893719;
    if (jetBin == 8) return 1.02789914608;
    if (jetBin == 9) return 1.25401544571;
    if (jetBin == 10) return 2.93627476692;
    if (jetBin == 11) return 0.856191754341;
    if (jetBin == 12) return 1.20744895935;
    return 0; // This never happens
}

float wtaunu_fac025_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.00406336784;
    if (jetBin == 2) return 1.03397119045;
    if (jetBin == 3) return 0.985612392426;
    if (jetBin == 4) return 0.915521025658;
    if (jetBin == 5) return 0.865237474442;
    if (jetBin == 6) return 0.889733076096;
    if (jetBin == 7) return 0.910926282406;
    if (jetBin == 8) return 0.889192461967;
    if (jetBin == 9) return 0.849098682404;
    if (jetBin == 10) return 0.90785241127;
    if (jetBin == 11) return 0.803071737289;
    if (jetBin == 12) return 1.08108282089;
    return 0; // This never happens
}

float wtaunu_fac025_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.30379629135;
    if (jetBin == 2) return 1.10970497131;
    if (jetBin == 3) return 1.07546174526;
    if (jetBin == 4) return 0.960847973824;
    if (jetBin == 5) return 0.878305912018;
    if (jetBin == 6) return 0.887533843517;
    if (jetBin == 7) return 0.914044976234;
    if (jetBin == 8) return 1.05813443661;
    if (jetBin == 9) return 0.898591995239;
    if (jetBin == 10) return 0.880031347275;
    if (jetBin == 11) return 1.05264282227;
    if (jetBin == 12) return 3.0896294117;
    return 0; // This never happens
}

float wtaunu_fac025_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.66293919086;
    if (jetBin == 2) return 1.07559406757;
    if (jetBin == 3) return 1.0889827013;
    if (jetBin == 4) return 0.972872197628;
    if (jetBin == 5) return 0.855378210545;
    if (jetBin == 6) return 0.877680838108;
    if (jetBin == 7) return 0.858337104321;
    if (jetBin == 8) return 0.852735161781;
    if (jetBin == 9) return 1.4500566721;
    if (jetBin == 10) return 0.826162576675;
    if (jetBin == 11) return 1.31084728241;
    if (jetBin == 12) return 0.575557351112;
    return 0; // This never happens
}

float wtaunu_fac025_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.66293919086;
    if (jetBin == 2) return 1.22467398643;
    if (jetBin == 3) return 0.991140186787;
    if (jetBin == 4) return 1.04841542244;
    if (jetBin == 5) return 0.917193055153;
    if (jetBin == 6) return 0.887084305286;
    if (jetBin == 7) return 1.3547757864;
    if (jetBin == 8) return 0.824084639549;
    if (jetBin == 9) return 1.79746389389;
    if (jetBin == 10) return 1.346778512;
    if (jetBin == 11) return 1.31084728241;
    if (jetBin == 12) return 0.0317593067884;
    return 0; // This never happens
}

float wtaunu_fac025_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.66293919086;
    if (jetBin == 2) return 1.2754149437;
    if (jetBin == 3) return 0.995674788952;
    if (jetBin == 4) return 0.882366538048;
    if (jetBin == 5) return 0.865684568882;
    if (jetBin == 6) return 0.775445044041;
    if (jetBin == 7) return 1.07983732224;
    if (jetBin == 8) return 0.730936586857;
    if (jetBin == 9) return 0.847517669201;
    if (jetBin == 10) return 0.572398245335;
    if (jetBin == 11) return 1.57208919525;
    if (jetBin == 12) return 0.0317593067884;
    return 0; // This never happens
}

float wtaunu_fac025_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.66293919086;
    if (jetBin == 2) return 1.67812907696;
    if (jetBin == 3) return 0.888825893402;
    if (jetBin == 4) return 0.89136070013;
    if (jetBin == 5) return 0.659919202328;
    if (jetBin == 6) return 0.954383015633;
    if (jetBin == 7) return 0.707641661167;
    if (jetBin == 8) return 1.02888739109;
    if (jetBin == 9) return 0.735209703445;
    if (jetBin == 10) return 0.834466159344;
    if (jetBin == 11) return 1.57208919525;
    if (jetBin == 12) return 0.0317593067884;
    return 0; // This never happens
}

float wtaunu_fac4_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.03263735771;
    if (jetBin == 2) return 1.00376152992;
    if (jetBin == 3) return 0.966211378574;
    if (jetBin == 4) return 0.940827310085;
    if (jetBin == 5) return 0.90907984972;
    if (jetBin == 6) return 0.913482308388;
    if (jetBin == 7) return 1.05369639397;
    if (jetBin == 8) return 0.896938204765;
    if (jetBin == 9) return 1.1369638443;
    if (jetBin == 10) return 0.729604065418;
    if (jetBin == 11) return 0.946973264217;
    if (jetBin == 12) return 1.46971201897;
    return 0; // This never happens
}

float wtaunu_fac4_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.974081754684;
    if (jetBin == 2) return 0.977685451508;
    if (jetBin == 3) return 0.943901181221;
    if (jetBin == 4) return 0.898146092892;
    if (jetBin == 5) return 0.82962667942;
    if (jetBin == 6) return 0.856816112995;
    if (jetBin == 7) return 0.991402208805;
    if (jetBin == 8) return 0.913291335106;
    if (jetBin == 9) return 1.01273095608;
    if (jetBin == 10) return 1.92880320549;
    if (jetBin == 11) return 0.987170100212;
    if (jetBin == 12) return 1.43466413021;
    return 0; // This never happens
}

float wtaunu_fac4_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.94722032547;
    if (jetBin == 2) return 0.969158291817;
    if (jetBin == 3) return 0.916691184044;
    if (jetBin == 4) return 0.849298238754;
    if (jetBin == 5) return 0.80825728178;
    if (jetBin == 6) return 0.825742006302;
    if (jetBin == 7) return 0.827176570892;
    if (jetBin == 8) return 0.824292361736;
    if (jetBin == 9) return 0.853956460953;
    if (jetBin == 10) return 0.812155008316;
    if (jetBin == 11) return 0.774199843407;
    if (jetBin == 12) return 0.869745612144;
    return 0; // This never happens
}

float wtaunu_fac4_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.34058237076;
    if (jetBin == 2) return 1.07900691032;
    if (jetBin == 3) return 1.0109256506;
    if (jetBin == 4) return 0.897563934326;
    if (jetBin == 5) return 0.827865004539;
    if (jetBin == 6) return 0.840299248695;
    if (jetBin == 7) return 0.869066298008;
    if (jetBin == 8) return 0.957416057587;
    if (jetBin == 9) return 0.804440319538;
    if (jetBin == 10) return 0.823744595051;
    if (jetBin == 11) return 1.16026031971;
    if (jetBin == 12) return 2.46441912651;
    return 0; // This never happens
}

float wtaunu_fac4_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.924506783485;
    if (jetBin == 2) return 1.06631529331;
    if (jetBin == 3) return 1.04292297363;
    if (jetBin == 4) return 0.901626527309;
    if (jetBin == 5) return 0.797043442726;
    if (jetBin == 6) return 0.810090243816;
    if (jetBin == 7) return 0.790922164917;
    if (jetBin == 8) return 0.7731757164;
    if (jetBin == 9) return 1.25464069843;
    if (jetBin == 10) return 0.771043479443;
    if (jetBin == 11) return 1.30935406685;
    if (jetBin == 12) return 0.393948882818;
    return 0; // This never happens
}

float wtaunu_fac4_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.924506783485;
    if (jetBin == 2) return 1.27475047112;
    if (jetBin == 3) return 0.960889995098;
    if (jetBin == 4) return 0.963938474655;
    if (jetBin == 5) return 0.86380058527;
    if (jetBin == 6) return 0.833915472031;
    if (jetBin == 7) return 1.22701048851;
    if (jetBin == 8) return 0.747391462326;
    if (jetBin == 9) return 1.60081267357;
    if (jetBin == 10) return 1.39158153534;
    if (jetBin == 11) return 1.30935406685;
    if (jetBin == 12) return 0.0371511988342;
    return 0; // This never happens
}

float wtaunu_fac4_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.924506783485;
    if (jetBin == 2) return 1.45961737633;
    if (jetBin == 3) return 0.933194816113;
    if (jetBin == 4) return 0.809507071972;
    if (jetBin == 5) return 0.770732939243;
    if (jetBin == 6) return 0.701740205288;
    if (jetBin == 7) return 0.934406816959;
    if (jetBin == 8) return 0.71946823597;
    if (jetBin == 9) return 0.859342455864;
    if (jetBin == 10) return 0.426131486893;
    if (jetBin == 11) return 1.46971201897;
    if (jetBin == 12) return 0.0371511988342;
    return 0; // This never happens
}

float wtaunu_fac4_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.924506783485;
    if (jetBin == 2) return 1.61884093285;
    if (jetBin == 3) return 0.994335472584;
    if (jetBin == 4) return 0.928640425205;
    if (jetBin == 5) return 0.641776800156;
    if (jetBin == 6) return 0.802202224731;
    if (jetBin == 7) return 0.635906219482;
    if (jetBin == 8) return 0.839347183704;
    if (jetBin == 9) return 0.478173583746;
    if (jetBin == 10) return 0.946973264217;
    if (jetBin == 11) return 1.46971201897;
    if (jetBin == 12) return 0.0371511988342;
    return 0; // This never happens
}

float wtaunu_qsf025_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.02348709106;
    if (jetBin == 2) return 1.01281523705;
    if (jetBin == 3) return 0.968326568604;
    if (jetBin == 4) return 0.956650733948;
    if (jetBin == 5) return 0.946258127689;
    if (jetBin == 6) return 0.93817025423;
    if (jetBin == 7) return 1.16250944138;
    if (jetBin == 8) return 1.0429930687;
    if (jetBin == 9) return 1.76555430889;
    if (jetBin == 10) return 0.466850101948;
    if (jetBin == 11) return 0.555507302284;
    if (jetBin == 12) return 1.01455068588;
    return 0; // This never happens
}

float wtaunu_qsf025_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.09470498562;
    if (jetBin == 2) return 1.15527045727;
    if (jetBin == 3) return 0.989719510078;
    if (jetBin == 4) return 0.922224462032;
    if (jetBin == 5) return 0.848845362663;
    if (jetBin == 6) return 0.892136931419;
    if (jetBin == 7) return 1.0224044323;
    if (jetBin == 8) return 0.951511204243;
    if (jetBin == 9) return 1.00617337227;
    if (jetBin == 10) return 1.61527764797;
    if (jetBin == 11) return 0.84049975872;
    if (jetBin == 12) return 1.44915938377;
    return 0; // This never happens
}

float wtaunu_qsf025_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.1709805727;
    if (jetBin == 2) return 1.17921996117;
    if (jetBin == 3) return 0.991274237633;
    if (jetBin == 4) return 0.898061394691;
    if (jetBin == 5) return 0.833117544651;
    if (jetBin == 6) return 0.837189853191;
    if (jetBin == 7) return 0.852205336094;
    if (jetBin == 8) return 0.851407647133;
    if (jetBin == 9) return 0.818641781807;
    if (jetBin == 10) return 0.810269236565;
    if (jetBin == 11) return 0.76557892561;
    if (jetBin == 12) return 0.666366040707;
    return 0; // This never happens
}

float wtaunu_qsf025_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.35750579834;
    if (jetBin == 2) return 1.22265517712;
    if (jetBin == 3) return 1.08250725269;
    if (jetBin == 4) return 0.963847339153;
    if (jetBin == 5) return 0.842038393021;
    if (jetBin == 6) return 0.836235761642;
    if (jetBin == 7) return 0.873409688473;
    if (jetBin == 8) return 1.00401353836;
    if (jetBin == 9) return 0.810186564922;
    if (jetBin == 10) return 0.89186501503;
    if (jetBin == 11) return 1.07503688335;
    if (jetBin == 12) return 3.39625263214;
    return 0; // This never happens
}

float wtaunu_qsf025_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.728233575821;
    if (jetBin == 2) return 1.1571187973;
    if (jetBin == 3) return 1.0998506546;
    if (jetBin == 4) return 0.96751844883;
    if (jetBin == 5) return 0.808519244194;
    if (jetBin == 6) return 0.817903757095;
    if (jetBin == 7) return 0.796376168728;
    if (jetBin == 8) return 0.762713074684;
    if (jetBin == 9) return 1.35637784004;
    if (jetBin == 10) return 0.728832006454;
    if (jetBin == 11) return 0.980313956738;
    if (jetBin == 12) return 0.396644443274;
    return 0; // This never happens
}

float wtaunu_qsf025_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.728233575821;
    if (jetBin == 2) return 1.29890096188;
    if (jetBin == 3) return 1.0022881031;
    if (jetBin == 4) return 1.0186882019;
    if (jetBin == 5) return 0.881728291512;
    if (jetBin == 6) return 0.842168033123;
    if (jetBin == 7) return 1.22482335567;
    if (jetBin == 8) return 0.747171878815;
    if (jetBin == 9) return 1.72296130657;
    if (jetBin == 10) return 1.34230411053;
    if (jetBin == 11) return 0.980313956738;
    if (jetBin == 12) return 0.0222945325077;
    return 0; // This never happens
}

float wtaunu_qsf025_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.728233575821;
    if (jetBin == 2) return 1.38070785999;
    if (jetBin == 3) return 0.971761584282;
    if (jetBin == 4) return 0.84830981493;
    if (jetBin == 5) return 0.794509589672;
    if (jetBin == 6) return 0.719988822937;
    if (jetBin == 7) return 1.02292835712;
    if (jetBin == 8) return 0.683405220509;
    if (jetBin == 9) return 0.882970631123;
    if (jetBin == 10) return 0.468501478434;
    if (jetBin == 11) return 2.06036067009;
    if (jetBin == 12) return 0.0222945325077;
    return 0; // This never happens
}

float wtaunu_qsf025_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.728233575821;
    if (jetBin == 2) return 1.54373705387;
    if (jetBin == 3) return 0.878510296345;
    if (jetBin == 4) return 0.899132430553;
    if (jetBin == 5) return 0.609670758247;
    if (jetBin == 6) return 0.835428476334;
    if (jetBin == 7) return 0.621158540249;
    if (jetBin == 8) return 0.898669183254;
    if (jetBin == 9) return 0.647530138493;
    if (jetBin == 10) return 0.555507302284;
    if (jetBin == 11) return 2.06036067009;
    if (jetBin == 12) return 0.0222945325077;
    return 0; // This never happens
}

float wtaunu_qsf4_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.03741967678;
    if (jetBin == 2) return 0.992589116096;
    if (jetBin == 3) return 0.96934568882;
    if (jetBin == 4) return 0.929206550121;
    if (jetBin == 5) return 0.911231458187;
    if (jetBin == 6) return 0.935705006123;
    if (jetBin == 7) return 1.12617099285;
    if (jetBin == 8) return 1.00233674049;
    if (jetBin == 9) return 1.62169837952;
    if (jetBin == 10) return 0.816929757595;
    if (jetBin == 11) return 0.835641205311;
    if (jetBin == 12) return 1.03005969524;
    return 0; // This never happens
}

float wtaunu_qsf4_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.895578801632;
    if (jetBin == 2) return 0.876631736755;
    if (jetBin == 3) return 0.903949439526;
    if (jetBin == 4) return 0.865749239922;
    if (jetBin == 5) return 0.844134390354;
    if (jetBin == 6) return 0.888948142529;
    if (jetBin == 7) return 0.992564797401;
    if (jetBin == 8) return 0.967100679874;
    if (jetBin == 9) return 1.14753544331;
    if (jetBin == 10) return 1.94782829285;
    if (jetBin == 11) return 1.32775485516;
    if (jetBin == 12) return 1.24127674103;
    return 0; // This never happens
}

float wtaunu_qsf4_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.855922102928;
    if (jetBin == 2) return 0.887660503387;
    if (jetBin == 3) return 0.876964390278;
    if (jetBin == 4) return 0.805489063263;
    if (jetBin == 5) return 0.810943722725;
    if (jetBin == 6) return 0.831785678864;
    if (jetBin == 7) return 0.847520947456;
    if (jetBin == 8) return 0.858519494534;
    if (jetBin == 9) return 0.801922082901;
    if (jetBin == 10) return 0.795800089836;
    if (jetBin == 11) return 1.18924343586;
    if (jetBin == 12) return 0.619572460651;
    return 0; // This never happens
}

float wtaunu_qsf4_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.09254515171;
    if (jetBin == 2) return 1.02052783966;
    if (jetBin == 3) return 0.987661778927;
    if (jetBin == 4) return 0.87134462595;
    if (jetBin == 5) return 0.832521140575;
    if (jetBin == 6) return 0.858290493488;
    if (jetBin == 7) return 0.880836069584;
    if (jetBin == 8) return 1.02789950371;
    if (jetBin == 9) return 0.900894701481;
    if (jetBin == 10) return 0.737307012081;
    if (jetBin == 11) return 0.996574580669;
    if (jetBin == 12) return 2.96866941452;
    return 0; // This never happens
}

float wtaunu_qsf4_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.35494339466;
    if (jetBin == 2) return 1.03401589394;
    if (jetBin == 3) return 1.04238319397;
    if (jetBin == 4) return 0.905047118664;
    if (jetBin == 5) return 0.829251110554;
    if (jetBin == 6) return 0.861573219299;
    if (jetBin == 7) return 0.849368035793;
    if (jetBin == 8) return 0.830431044102;
    if (jetBin == 9) return 1.38234853745;
    if (jetBin == 10) return 0.843547523022;
    if (jetBin == 11) return 1.09509551525;
    if (jetBin == 12) return 0.379041641951;
    return 0; // This never happens
}

float wtaunu_qsf4_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.35494339466;
    if (jetBin == 2) return 1.23266863823;
    if (jetBin == 3) return 0.992636084557;
    if (jetBin == 4) return 0.969281494617;
    if (jetBin == 5) return 0.909804821014;
    if (jetBin == 6) return 0.867386519909;
    if (jetBin == 7) return 1.28642714024;
    if (jetBin == 8) return 0.807869613171;
    if (jetBin == 9) return 1.70077264309;
    if (jetBin == 10) return 1.38518750668;
    if (jetBin == 11) return 1.09509551525;
    if (jetBin == 12) return 0.0356368012726;
    return 0; // This never happens
}

float wtaunu_qsf4_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.35494339466;
    if (jetBin == 2) return 1.37709641457;
    if (jetBin == 3) return 0.945185303688;
    if (jetBin == 4) return 0.840161979198;
    if (jetBin == 5) return 0.787679314613;
    if (jetBin == 6) return 0.766739308834;
    if (jetBin == 7) return 1.04762506485;
    if (jetBin == 8) return 0.706145048141;
    if (jetBin == 9) return 0.940883100033;
    if (jetBin == 10) return 0.581859827042;
    if (jetBin == 11) return 2.56305766106;
    if (jetBin == 12) return 0.0356368012726;
    return 0; // This never happens
}

float wtaunu_qsf4_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.35494339466;
    if (jetBin == 2) return 1.70509314537;
    if (jetBin == 3) return 0.977085709572;
    if (jetBin == 4) return 0.949401438236;
    if (jetBin == 5) return 0.661776840687;
    if (jetBin == 6) return 0.937375605106;
    if (jetBin == 7) return 0.728156447411;
    if (jetBin == 8) return 0.97258657217;
    if (jetBin == 9) return 0.612798750401;
    if (jetBin == 10) return 0.835641205311;
    if (jetBin == 11) return 2.56305766106;
    if (jetBin == 12) return 0.0356368012726;
    return 0; // This never happens
}

float wtaunu_renorm025_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.02510869503;
    if (jetBin == 2) return 1.02909111977;
    if (jetBin == 3) return 1.1191983223;
    if (jetBin == 4) return 1.25266754627;
    if (jetBin == 5) return 1.38642096519;
    if (jetBin == 6) return 1.3946274519;
    if (jetBin == 7) return 1.68345284462;
    if (jetBin == 8) return 1.55612671375;
    if (jetBin == 9) return 1.79157531261;
    if (jetBin == 10) return 1.02394449711;
    if (jetBin == 11) return 0.763024806976;
    if (jetBin == 12) return 2.04049301147;
    return 0; // This never happens
}

float wtaunu_renorm025_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.06939589977;
    if (jetBin == 2) return 1.01998066902;
    if (jetBin == 3) return 1.10338544846;
    if (jetBin == 4) return 1.23553645611;
    if (jetBin == 5) return 1.27293670177;
    if (jetBin == 6) return 1.35313022137;
    if (jetBin == 7) return 1.50756347179;
    if (jetBin == 8) return 1.45848417282;
    if (jetBin == 9) return 1.54003608227;
    if (jetBin == 10) return 3.08838653564;
    if (jetBin == 11) return 1.90247559547;
    if (jetBin == 12) return 3.02123332024;
    return 0; // This never happens
}

float wtaunu_renorm025_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.98731136322;
    if (jetBin == 2) return 0.995178341866;
    if (jetBin == 3) return 1.06801021099;
    if (jetBin == 4) return 1.15756738186;
    if (jetBin == 5) return 1.21254515648;
    if (jetBin == 6) return 1.26443111897;
    if (jetBin == 7) return 1.28763353825;
    if (jetBin == 8) return 1.27094316483;
    if (jetBin == 9) return 1.26856136322;
    if (jetBin == 10) return 1.19702458382;
    if (jetBin == 11) return 0.940341413021;
    if (jetBin == 12) return 1.2470459938;
    return 0; // This never happens
}

float wtaunu_renorm025_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.25641727448;
    if (jetBin == 2) return 1.04386782646;
    if (jetBin == 3) return 1.14736688137;
    if (jetBin == 4) return 1.22796535492;
    if (jetBin == 5) return 1.23871159554;
    if (jetBin == 6) return 1.29093205929;
    if (jetBin == 7) return 1.35630941391;
    if (jetBin == 8) return 1.49639642239;
    if (jetBin == 9) return 1.32065200806;
    if (jetBin == 10) return 1.29823410511;
    if (jetBin == 11) return 1.78784716129;
    if (jetBin == 12) return 4.11794757843;
    return 0; // This never happens
}

float wtaunu_renorm025_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.796396791935;
    if (jetBin == 2) return 1.03301465511;
    if (jetBin == 3) return 1.16245651245;
    if (jetBin == 4) return 1.23248314857;
    if (jetBin == 5) return 1.19811856747;
    if (jetBin == 6) return 1.25215220451;
    if (jetBin == 7) return 1.21811747551;
    if (jetBin == 8) return 1.19375514984;
    if (jetBin == 9) return 1.87635600567;
    if (jetBin == 10) return 1.27878403664;
    if (jetBin == 11) return 1.53797364235;
    if (jetBin == 12) return 0.686533272266;
    return 0; // This never happens
}

float wtaunu_renorm025_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.796396791935;
    if (jetBin == 2) return 1.12374770641;
    if (jetBin == 3) return 1.01478993893;
    if (jetBin == 4) return 1.22875881195;
    if (jetBin == 5) return 1.18497443199;
    if (jetBin == 6) return 1.17972683907;
    if (jetBin == 7) return 1.73925077915;
    if (jetBin == 8) return 1.06345748901;
    if (jetBin == 9) return 2.24881339073;
    if (jetBin == 10) return 1.88163173199;
    if (jetBin == 11) return 1.53797364235;
    if (jetBin == 12) return 0.0549962110817;
    return 0; // This never happens
}

float wtaunu_renorm025_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.796396791935;
    if (jetBin == 2) return 1.48642897606;
    if (jetBin == 3) return 0.980642199516;
    if (jetBin == 4) return 1.11249411106;
    if (jetBin == 5) return 1.13739478588;
    if (jetBin == 6) return 1.08004879951;
    if (jetBin == 7) return 1.47546589375;
    if (jetBin == 8) return 1.03703808784;
    if (jetBin == 9) return 1.11202514172;
    if (jetBin == 10) return 0.796731412411;
    if (jetBin == 11) return 2.04049301147;
    if (jetBin == 12) return 0.0549962110817;
    return 0; // This never happens
}

float wtaunu_renorm025_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.796396791935;
    if (jetBin == 2) return 1.60954368114;
    if (jetBin == 3) return 1.11422944069;
    if (jetBin == 4) return 1.18523454666;
    if (jetBin == 5) return 0.900903999805;
    if (jetBin == 6) return 1.16726541519;
    if (jetBin == 7) return 0.930123090744;
    if (jetBin == 8) return 1.18448376656;
    if (jetBin == 9) return 0.853473603725;
    if (jetBin == 10) return 0.763024806976;
    if (jetBin == 11) return 2.04049301147;
    if (jetBin == 12) return 0.0549962110817;
    return 0; // This never happens
}

float wtaunu_renorm4_0to70(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.03604710102;
    if (jetBin == 2) return 0.982883095741;
    if (jetBin == 3) return 0.875595867634;
    if (jetBin == 4) return 0.77132999897;
    if (jetBin == 5) return 0.692318916321;
    if (jetBin == 6) return 0.68190830946;
    if (jetBin == 7) return 0.807059645653;
    if (jetBin == 8) return 0.715126216412;
    if (jetBin == 9) return 0.935657441616;
    if (jetBin == 10) return 0.320431619883;
    if (jetBin == 11) return 0.4734980762;
    if (jetBin == 12) return 2.754155159;
    return 0; // This never happens
}

float wtaunu_renorm4_70to140(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.934100389481;
    if (jetBin == 2) return 0.957465469837;
    if (jetBin == 3) return 0.863263309002;
    if (jetBin == 4) return 0.737389266491;
    if (jetBin == 5) return 0.617579758167;
    if (jetBin == 6) return 0.634509265423;
    if (jetBin == 7) return 0.703330218792;
    if (jetBin == 8) return 0.660853028297;
    if (jetBin == 9) return 0.737937867641;
    if (jetBin == 10) return 1.40821611881;
    if (jetBin == 11) return 0.946850776672;
    if (jetBin == 12) return 0.956591069698;
    return 0; // This never happens
}

float wtaunu_renorm4_140to280(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 0.92585426569;
    if (jetBin == 2) return 0.960438728333;
    if (jetBin == 3) return 0.838027119637;
    if (jetBin == 4) return 0.687215089798;
    if (jetBin == 5) return 0.60646045208;
    if (jetBin == 6) return 0.592621743679;
    if (jetBin == 7) return 0.611398398876;
    if (jetBin == 8) return 0.603706717491;
    if (jetBin == 9) return 0.607352852821;
    if (jetBin == 10) return 0.62896746397;
    if (jetBin == 11) return 0.593275368214;
    if (jetBin == 12) return 0.82121193409;
    return 0; // This never happens
}

float wtaunu_renorm4_280to500(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 1.14646875858;
    if (jetBin == 2) return 1.07697832584;
    if (jetBin == 3) return 0.930714488029;
    if (jetBin == 4) return 0.724286496639;
    if (jetBin == 5) return 0.612920582294;
    if (jetBin == 6) return 0.610924422741;
    if (jetBin == 7) return 0.633555352688;
    if (jetBin == 8) return 0.718675136566;
    if (jetBin == 9) return 0.599683046341;
    if (jetBin == 10) return 0.597106575966;
    if (jetBin == 11) return 0.619540214539;
    if (jetBin == 12) return 2.12776112556;
    return 0; // This never happens
}

float wtaunu_renorm4_500to700(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 2.07682871819;
    if (jetBin == 2) return 1.06634294987;
    if (jetBin == 3) return 0.951306939125;
    if (jetBin == 4) return 0.724844276905;
    if (jetBin == 5) return 0.591718733311;
    if (jetBin == 6) return 0.598014593124;
    if (jetBin == 7) return 0.573224186897;
    if (jetBin == 8) return 0.575217366219;
    if (jetBin == 9) return 0.958556652069;
    if (jetBin == 10) return 0.650491535664;
    if (jetBin == 11) return 0.746574521065;
    if (jetBin == 12) return 0.453287661076;
    return 0; // This never happens
}

float wtaunu_renorm4_700to1000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 2.07682871819;
    if (jetBin == 2) return 1.23899161816;
    if (jetBin == 3) return 0.891665399075;
    if (jetBin == 4) return 0.798153460026;
    if (jetBin == 5) return 0.643373727798;
    if (jetBin == 6) return 0.632496237755;
    if (jetBin == 7) return 0.94984382391;
    if (jetBin == 8) return 0.542187511921;
    if (jetBin == 9) return 1.30247402191;
    if (jetBin == 10) return 1.0508607626;
    if (jetBin == 11) return 0.746574521065;
    if (jetBin == 12) return 0.0232734847814;
    return 0; // This never happens
}

float wtaunu_renorm4_1000to2000(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 2.07682871819;
    if (jetBin == 2) return 1.3954488039;
    if (jetBin == 3) return 0.874539315701;
    if (jetBin == 4) return 0.682577610016;
    if (jetBin == 5) return 0.591794729233;
    if (jetBin == 6) return 0.51074308157;
    if (jetBin == 7) return 0.728288590908;
    if (jetBin == 8) return 0.507706046104;
    if (jetBin == 9) return 0.626698553562;
    if (jetBin == 10) return 0.384184122086;
    if (jetBin == 11) return 0.778892993927;
    if (jetBin == 12) return 0.0232734847814;
    return 0; // This never happens
}

float wtaunu_renorm4_2000toECMS(int nTruthJets)
{
    int jetBin = nTruthJets+1;
    if (jetBin > 12) jetBin = 12;
    if (jetBin == 1) return 2.07682871819;
    if (jetBin == 2) return 1.75131988525;
    if (jetBin == 3) return 0.871731758118;
    if (jetBin == 4) return 0.700257301331;
    if (jetBin == 5) return 0.464166283607;
    if (jetBin == 6) return 0.613311350346;
    if (jetBin == 7) return 0.450641393661;
    if (jetBin == 8) return 0.619004249573;
    if (jetBin == 9) return 0.302531421185;
    if (jetBin == 10) return 0.4734980762;
    if (jetBin == 11) return 0.778892993927;
    if (jetBin == 12) return 0.0232734847814;
    return 0; // This never happens
}

